---
- name: Get fact dotfiles path
  file:
    path: "{{ dotfiles_root_path }}"
    state: directory
    mode: 0755

- name: "Ensure XDG_DATA_DIR ({{ xdg_data_dir }}) present"
  file:
    path: "{{ xdg_data_dir }}"
    state: directory
    mode: 0755

- name: "Ensure XDG_CONFIG_DIR ({{ xdg_config_dir }}) present"
  file:
    path: "{{ xdg_config_dir }}"
    state: directory
    mode: 0755

- include_tasks: prepare_remote_dotfiles.yml
  with_items:
    - { remote: "{{ bash_repo_name }}", local_subdir: "{{ bash_dotfiles_dir_name }}" }
    - { remote: "{{ vim_repo_name }}", local_subdir: "{{ vim_dotfiles_dir_name }}" }
    - { remote: "{{ nvim_repo_name }}", local_subdir: "{{ nvim_dotfiles_dir_name }}" }
    - { remote: "{{ tmux_repo_name }}", local_subdir: "{{ tmux_dotfiles_dir_name }}" }
    - { remote: "{{ alacritty_repo_name }}", local_subdir: "{{ alacritty_dotfiles_dir_name }}" }
    - { remote: "{{ i3_repo_name }}", local_subdir: "{{ i3_dotfiles_dir_name }}" }
  loop_control:
    loop_var: repo
