---
# TODO get these facts right
- name: Get facts about local FZF if any
  ignore_errors: true
  stat:
    path: "{{ fzf_root_path }}/bin/fzf"
  register: fzf_exists
  changed_when: false

# - name: Include fzf task vars
#   include_vars:
#     file: fzf.yml
#     name: fzf

# TODO create a proper become for homebrew
- name: Download fzf tarball
  unarchive:
    src: "{{ fzf_url }}"
    dest: "{{ fzf_root_parent }}"
    remote_src: true
  when: not fzf_use_pkg_mgr and not fzf_exists.stat.exists

- name: Rename fzf directory
  command: mv "fzf-{{ fzf_version }}" fzf
  args:
    chdir: "{{ fzf_parent }}"
  when: not fzf_exists.stat.exists

- name: Modify fzf install script with prefix in vars
  lineinfile:
    path: "{{ fzf_root_path }}/install"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^prefix=", line: "prefix='{{ fzf_root_path }}'" }
    - { regexp: "^prefix_expand=", line: "prefix={{ fzf_root_path }}" }

- name: Execute fzf install script
  command:
  args:
    argv:
      - "{{ fzf_root_path }}/install"
      - --xdg
      - --completion
      - --key-bindings
      - --no-update-rc

