---
- name: Link vimrc to expected location
  file:
    state: link
    src: "{{ vim_dotfiles_root_path }}/vimrc"
    dest: ~/.vimrc
    force: true

- name: Link vim dir to expected location (home)
  file:
    state: link
    src: "{{ vim_dotfiles_root_path }}"
    dest: ~/.vim
    force: true
