---
- name: Link tmux.conf to expected location
  file:
    state: link
    src: "{{ tmux_dotfiles_root_path }}/.tmux.conf"
    dest: ~/.tmux.conf
    force: true

- name: Link tmux.conf.local to expected location
  file:
    state: link
    src: "{{ tmux_dotfiles_root_path }}/.tmux.conf.local"
    dest: ~/.tmux.conf.local
    force: true
