# TODO consider including XDG Xauthority and the like
# TODO instead of these complicated steps, use agent forwarding and only use the ssh link to the repo
# TODO: Bash should be in here since it's an env thing & is needed before installing things like go/rust/nvm/npm/node
---
# - import_tasks: home_dirs.yml
#   tags:
#     - env
#     - directory

# - import_tasks: clone_dotfiles.yml
#   tags:
#     - dotfiles

# - import_tasks: link_bash_dotfiles.yml
#   tags:
#     - dotfiles
#     - bash

# - import_tasks: python_env.yml
#   tags:
#     - python

# - import_tasks: link_vim_dotfiles.yml
#   tags:
#     - dotfiles
#     - vim

# - import_tasks: link_neovim_dotfiles.yml
#   tags:
#     - dotfiles
#     - neovim
#
# - import_tasks: link_tmux_dotfiles.yml
#   tags:
#     - dotfiles
#     - tmux
#
# - import_tasks: link_alacritty_dotfiles.yml
#   tags:
#     - dotfiles
#     - alacritty

# - import_tasks: nvm.yml
#   tags:
#     - dev_env
#     - nvm
#
# - include: nvm_permissions.yml
#   tags:
#     - dev_env
#     - nvm
#
# - import_tasks: node.yml
#   tags:
#     - dev_env
#     - node



# TODO handle these later
# - import_tasks: go.yml
#   when: go_enable
#   tags: [go, install, env]


# - import_tasks: fzf.yml
#   when: fzf_enable
#   tags: [fzf, cli]


- import_tasks: rustup.yml
  when: rust_enable
  tags: [rustup, cargo, env, install]
