---
- name: Install python3
  package:
    name: python
    state: present

- name: Install pip3
  package:
    name: python-pip
    state: present

- name: Install base (user) pip packages
  pip:
    name: "{{ cli_app_pip_deps }}"
    extra_args: --user
    