---
# TODO configure the environment vars to change location
# details here https://bit.ly/2G7fjnl
- name: Get facts about cargo
  stat:
    path: "{{ cargo_path }}/bin/cargo"
  register: cargo_exists
  changed_when: false

# ===== execute this only when we don't have cargo installed ====
- block:

  - name: Create cargo directory
    file:
      path: "{{ cargo_path }}"
      state: directory
      mode: 0755

  - name: Download rustup.sh
    get_url:
      url: https://sh.rustup.rs
      dest: "{{ cargo_path }}"
      mode: 0755

  - name: Run rustup-init.sh from download
    command:
    args:
      argv:
        - "{{ cargo_path }}/rustup-init.sh"
        - --no-modify-path
        - -y

  when: not cargo_exists.stat.exists
